### ISSUE TITLE
zip files?

### ISSUE THREAD

**Issue by FaultyPine** [sinshutu/upload-to-discord#4]
I'm trying to upload a zipped file to discord, and get this error:

curl: (26) Failed to open/read local data from file/application
##[error]Docker run failed with exit code 26

is this an issue on my end? 
Also having the ability to upload folders (that automatically get zipped) would be amazing if possible on your end.

**Comment by sinshutu** [comment]
Thank you for information!
I'll check it later.

**Comment by sinshutu** [comment]
@FaultyPine 

There may be a problem with using curl.
For example, docker is not installed as a zip file because it decompresses when you add zip.
If possible, I want to describe actions

**Comment by FaultyPine** [comment]
Is there a way to upload a zip to discord correctly then?

**Comment by sinshutu** [comment]
I was able to upload a zip file with this description.


.github/workflows/main.yml
```
on: push
name: Main workflow
jobs:
  github-action:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Send file README.md to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: out.zip
```
