### ISSUE TITLE
curl: (26) Failed to open/read local data from file/application

### ISSUE THREAD

**Issue by TotalLag** [sinshutu/upload-to-discord#6]
Getting the following error when I am trying to send an image.  My config:

```
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Send image to discord channel
      uses: sinshutu/upload-to-discord@master
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      with:
        args: element.png
```
